baseURL = 'https://halibut205.github.io/Halibut_ONAP_Solution_Research/'
languageCode = 'vi-VN'
title = 'Halibut - ONAP Research'
theme = 'PaperMod'

[params]
  defaultTheme = "auto" # Tự động sáng/tối theo trình duyệt
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true # Cực kỳ cần thiết để copy code

# Hiển thị phần giới thiệu ở ngay trang chủ
[params.profileMode]
  enabled = true
  title = "Halibut's ONAP Workspace"
  subtitle = "Tài liệu nghiên cứu, cấu hình và triển khai kiến trúc ONAP."
