baseURL = 'https://halibut205.github.io/Halibut_ONAP_Solution_Research/'
languageCode = 'vi-VN'
title = 'What The Frick is ONAP'
theme = "PaperMod"

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[params]
  env = "production"
  description = "Ghi chép nghiên cứu và triển khai ONAP"
  author = "Halibut"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = false
  mainSections = ["deploy-onap", "kiến-trúc-onap"]
  hideFooter = false
  ShowBreadCrumbs = true

[[params.socialIcons]]
  name = "x"
  url = "https://x.com"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/halibut205"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com"

[[params.socialIcons]]
  name = "reddit"
  url = "https://reddit.com"

[params.homeInfoParams]
  Title = "What The Frick is ONAP"
  Content = "Tài liệu nghiên cứu kiến trúc và triển khai ONAP"

[[menu.main]]
  identifier = "posts"
  name = "Bài viết"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "deploy"
  name = "Triển Khai"
  url = "/deploy-onap/"
  weight = 20

[[menu.main]]
  identifier = "architecture"
  name = "Kiến trúc"
  url = "/kiến-trúc-onap/"
  weight = 30
